//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Requests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public System.DateTime RequestDateAdd { get; set; }
        public string RequestMachine { get; set; }
        public int RequestType { get; set; }
        public string RequestDescription { get; set; }
        public int RequestClient { get; set; }
        public int RequestStatus { get; set; }
    
        public virtual Repair Repair { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeOfRequest TypeOfRequest { get; set; }
        public virtual User User { get; set; }
    }
}
